apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: crv61l6u5-nodejs
  janus-idp.io/tekton: crv61l6u5-nodejs
  backstage.io/kubernetes-id: crv61l6u5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: crv61l6u5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
